name: ambilytics_example
description: Ambilytics example
ublish_to: 'none' 
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  firebase_core: ^3.4.0
  shared_preferences: ^2.2.0
  ambilytics:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true